### ISSUE TITLE
`Error: Failed to construct URL` when calling initPreviews()

### ISSUE THREAD

**Issue by akrolsmir** [Stvad/link-summoner#4]
![image](https://user-images.githubusercontent.com/856034/169043599-d7dd1a3d-3122-4659-866c-0042fe0d3f20.png)

I'm unable to call initPreviews() as a function, I think because it's running into some error case. See: https://github.com/manifoldmarkets/manifold/pull/150

**Comment by akrolsmir** [comment]
Repro case: https://manifold-git-link-summoner-mantic.vercel.app/AustinChen/whats-up prints out `undefined` in the console

**Comment by Stvad** [comment]
Hmm @akrolsmir , live previews work for me on that page 🙈. what browser are you using?

**Comment by Stvad** [comment]
Ok, so this works in FF and breaks in Chrome 🤔

**Comment by Stvad** [comment]
Also, I find it weird that this references the "browser" file instead of the "main" file (which is supposed to be the one picked up in the node env). browser is the one that would do automatic init on import 🤔

**Comment by Stvad** [comment]
huh, so it seems it's not that the previews don't work in chrome, but that Manifold crashes when run in iframe in Chrome! 
![link-summoner-manifold-crash](https://user-images.githubusercontent.com/81347/169167024-a5ad4aef-9759-42c9-81bb-f8a2fda92f3c.gif)


```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at J (https://manifold.markets/_next/static/chunks/6314-26be9c44fbae4e45.js:1:11663)
    at Object.643 (https://manifold.markets/_next/static/chunks/1042-bd3f335e02f40c5d.js:1:64097)
    at r (https://manifold.markets/_next/static/chunks/webpack-a146a8ef8f1e9d05.js:1:149)
    at Object.87997 (https://manifold.markets/_next/static/chunks/1042-bd3f335e02f40c5d.js:1:6792)
    at r (https://manifold.markets/_next/static/chunks/webpack-a146a8ef8f1e9d05.js:1:149)
    at Object.91765 (https://manifold.markets/_next/static/chunks/1042-bd3f335e02f40c5d.js:1:54558)
    at r (https://manifold.markets/_next/static/chunks/webpack-a146a8ef8f1e9d05.js:1:149)
    at Object.96131 (https://manifold.markets/_next/static/chunks/1042-bd3f335e02f40c5d.js:1:29874)
    at r (https://manifold.markets/_next/static/chunks/webpack-a146a8ef8f1e9d05.js:1:149)
    at Object.63953 (https://manifold.markets/_next/static/chunks/1042-bd3f335e02f40c5d.js:1:27021)
```

**Comment by Stvad** [comment]
Nvm that's a red-herring: (https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni) but fyi @akrolsmir iframes for Manifold won't work in Chrome incognito mode.

That said, now running test in a normal-chrome and it just works 🤔

**Comment by Stvad** [comment]
ok, my current guess is that your bundler gets the wrong bundle because of https://github.com/defunctzombie/package-browser-field-spec

**Comment by Stvad** [comment]
@akrolsmir I pushed 1.3.1 under that hypothesis. can you test it and lmk if that helped?

**Comment by Stvad** [comment]
also previews on https://manifold-git-link-summoner-mantic.vercel.app/AustinChen/whats-up still just work for me both in FF/non-private chrome

**Comment by Stvad** [comment]
@akrolsmir poke? 🙂

**Comment by Stvad** [comment]
on talking with Austin IRL: the fix seems to have helped with bundler pickign up the appropriate file. 

The error in the original report can still happen, but it's not actually impacting the functioning of the link-summoner and won't occur in the prod. It's next.js way of displayign unhandled promise errors
